name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Upload Binary to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_DEFAULT_REGION: "ap-south-1"
      run: |
        aws s3 cp ./main.go s3://${{ secrets.TARGET_BUCKET }}/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download S3
      uses: joutvhu/download-s3@v1.0.0
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_KEY }}
        aws_region: "eu-central-1"
        aws_bucket: ${{ secrets.TARGET_BUCKET }}
        target: .
    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: 13.235.71.241
        user: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        scp: ./main.go => /home/ec2-user/app/main.go
        last_ssh: chmod +x /home/ec2-user/app/main.go